version: '3.3'

services:
  configserver:
    container_name: configServer
    image: taehopark/luckyseven-configserver
    build:
      context: backend/configServer
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:8080"
    networks:
      - jenkins-network

networks:
  jenkins-network:
    external: true
